const variationsConstants = {
  GET_VARIATIONS_REQUEST: 'GET_VARIATIONS_REQUEST',
  GET_VARIATIONS_SUCCESS: 'GET_VARIATIONS_SUCCESS',
  GET_VARIATIONS_FAILURE: 'GET_VARIATIONS_FAILURE',
  SER_QUERY_MODE: 'SER_QUERY_MODE',
  COPY_VARIATIONS: 'COPY_VARIATIONS',
  REARRANGEMENT_VARIATIONS: 'REARRANGEMENT_VARIATIONS',
};

export default variationsConstants;
