const variationsConstants = {
  GET_VARIATIONS_REQUEST: 'GET_VARIATIONS_REQUEST',
  GET_VARIATIONS_SUCCESS: 'GET_VARIATIONS_SUCCESS',
  GET_VARIATIONS_FAILURE: 'GET_VARIATIONS_FAILURE',
  SET_QUERY_MODE: 'SET_QUERY_MODE',
  COPY_VARIATIONS: 'COPY_VARIATIONS',
  REARRANGEMENT_VARIATIONS: 'REARRANGEMENT_VARIATIONS',
  CLEAR_VARIATIONS: 'CLEAR_VARIATIONS',
  COPY_WORD: 'COPY_WORD',
};

export default variationsConstants;
